# Generated by Django 5.2 on 2025-05-06 00:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
    ]
